import { Task } from '@/types'

export function generateDemoTasks(): Task[] {
  const today = new Date()
  const tomorrow = new Date(today)
  tomorrow.setDate(tomorrow.getDate() + 1)

  return [
    {
      id: '1',
      ownerId: 'demo-user',
      title: 'Morning Run',
      description: 'Run 5km in the park',
      startTime: new Date(today.setHours(7, 0, 0)),
      endTime: new Date(today.setHours(8, 0, 0)),
      duration: 60,
      priority: 'medium',
      status: 'completed',
      assignees: [],
      tags: ['health', 'exercise'],
      pomodoroSessions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '2',
      ownerId: 'demo-user',
      title: 'Team Meeting',
      description: 'Weekly sync with the development team',
      startTime: new Date(today.setHours(10, 0, 0)),
      endTime: new Date(today.setHours(11, 0, 0)),
      duration: 60,
      priority: 'high',
      status: 'pending',
      assignees: [],
      tags: ['work', 'meeting'],
      pomodoroSessions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '3',
      ownerId: 'demo-user',
      title: 'Code Review',
      description: 'Review pull requests from yesterday',
      startTime: new Date(today.setHours(14, 0, 0)),
      duration: 30,
      priority: 'medium',
      status: 'pending',
      assignees: [],
      tags: ['work', 'development'],
      pomodoroSessions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '4',
      ownerId: 'demo-user',
      title: 'Buy Groceries',
      description: 'Milk, bread, eggs, vegetables',
      priority: 'low',
      status: 'pending',
      location: {
        lat: 40.7128,
        lng: -74.0060,
        address: 'Whole Foods Market, 250 7th Ave, New York',
        enabled: true,
      },
      assignees: [],
      tags: ['shopping', 'personal'],
      pomodoroSessions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '5',
      ownerId: 'demo-user',
      title: 'Workout Session',
      description: 'Complete daily workout routine',
      priority: 'medium',
      status: 'pending',
      stepTrigger: {
        threshold: 5000,
        enabled: true,
        source: 'approximation',
      },
      assignees: [],
      tags: ['health', 'fitness'],
      pomodoroSessions: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]
}
